# Build the project using the Bitcraze builder docker image
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check and build
      run: docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build 
